### ISSUE TITLE
refactor code

### ISSUE THREAD

**Issue by coldenate** [coldenate/remcord#12]
just need to refactor and clean up the code. 
if you see comments, or general stuff that you believe is not neccesary or can be refactored, feel free to open a pr!

**Comment by Subham5401** [comment]
Hi, I'd like to take this further.

**Comment by coldenate** [comment]
Hi yes, thank you for showing interest. @Subham5401 
Feel free to subscribe to this conversation, but for now I need to close this issue. 
I made the mistake of opening it up when I wasn't quite thinking about the current state of the code not being ready for strict refactoring. This is my first open source project with a contrib, so I hope you understand my novel mistakes. 😭
